# Generated by Django 5.0.1 on 2025-07-30 09:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_request_time', models.DateTimeField(auto_now=True)),
                ('request_count', models.IntegerField(default=0)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['user', 'farm'], name='chatbotapi__user_id_1a90e6_idx'), models.Index(fields=['timestamp'], name='chatbotapi__timesta_8eb05a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'farm_name'], name='chatbotapi__user_id_729fd6_idx'), models.Index(fields=['timestamp'], name='chatbotapi__timesta_cb99d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_history', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_histories', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'farm'], name='chatbotapi__user_id_20ca8f_idx')],
            },
        ),
    ]
